config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  # get '/:locale' => 'home#index'
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # action home page
  get '/posts', to: "home#index_show_post", as: 'posts_index'
  post '/posts', to: "home#index_show_post", as: 'get_post_index_pagy'
  get '/videos', to: "home#index_show_video", as: 'videos_index'
  post '/videos', to: "home#index_show_video", as: 'get_video_index_pagy'

  # action admin
  namespace 'admin' do
    get :index_ban_user, to: "users#index_ban_user"
    resources :users do
      member do
        get :action_ban_user
        get :action_unban_user
        post :ban_user
        post :unban_user
      end
    end
    resources :posts do
      member do
        get :action_accept_post
        get :action_refuse_post
        post :accept_post
        post :refuse_post
      end
    end
    resources :videos do
      member do
        get :action_accept_video
        get :action_refuse_video
        post :accept_video
        post :refuse_video
      end
    end
  end

  # action user
  scope '/users' do
    resources :posts do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_post
      end
      resources :elements
      resources :comments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
    resources :videos do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_video
      end
      resources :vcomments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
  end

  resources :chats do
    resources :messages
  end
  resources :tags do
    member do
      post :show, as: 'get_posts_tag_index_pagy'
      get :show_video
      post :show_video, as: 'get_videos_tag_index_pagy'
      post :added_tag
    end
  end
  resources :profile, only:  [:show] do
    member do
      post :follow
      delete :unfollow
      get :action_report_user
      post :report_user
    end
  end
  resources :dashboard do
    collection do
      # get :user_followers
      get :following_tags
      get :following_users
      get :posts_bookmark
      post :posts_bookmark, as: 'get_posts_dashboard_pagy'
      get :videos_bookmark
      post :videos_bookmark, as: 'get_videos_dashboard_pagy'
      get :notifications
    end
  end

  # action search
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get 'search', to: 'search#search_all', as: 'search_all'
  get 'show_all_user_search', to: 'search#show_all_user_search', as: :show_all_user_search

  # View Object Notification
  get '/notification/:id', to: 'notification#view_object', as: 'view_object'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @follower = current_user.follower
  end

  def following_users
    @followee = current_user.followee
  end

  def following_tags
    @tags = current_user.tags
  end

  def posts_bookmark
    data_post = set_data_post
    case params[:index]
    when "top"
      @pagy, @posts = pagy(data_post.where(published: true).distinct.order(cached_weighted_like_score: :desc,total_views: :desc), items: POSTS_PER_PAGE)
    when "oldest"
      @pagy, @posts = pagy(data_post.where(published: true).distinct.order(created_at: :asc,total_views: :desc), items: POSTS_PER_PAGE)
    when "newest"
      @pagy, @posts = pagy(data_post.where(published: true).distinct.order(created_at: :desc,total_views: :desc), items: POSTS_PER_PAGE)
    else
      @pagy, @posts = pagy(data_post.where(published: true).order(total_views: :desc).distinct, items: POSTS_PER_PAGE)
    end
    # sleep(1)
    respond_to do |format|
      format.html # GET
      format.turbo_stream # POST
    end
  end

  def videos_bookmark
    data_video = set_data_video
    case params[:index]
    when "top"
      @pagy, @videos = pagy(data_video.where(published: true).distinct.order(cached_weighted_like_score: :desc,total_views: :desc), items: VIDEOS_PER_PAGE)
    when "oldest"
      @pagy, @videos = pagy(data_video.where(published: true).distinct.order(created_at: :asc,total_views: :desc), items: VIDEOS_PER_PAGE)
    when "newest"
      @pagy, @videos = pagy(data_video.where(published: true).distinct.order(created_at: :desc,total_views: :desc), items: VIDEOS_PER_PAGE)
    else
      @pagy, @videos = pagy(data_video.where(published: true).order(total_views: :desc).distinct, items: VIDEOS_PER_PAGE)
    end
    # sleep(1)
    respond_to do |format|
      format.html # GET
      format.turbo_stream # POST
    end
  end

  def notifications
    @notifications = current_user.received_notifications.order(created_at: :desc).page(params[:page]).per(15)
  end

  private

  def set_data_post
    if params[:query].present?
      Post.bookmarked_by_user(current_user).ransack(title_or_description_cont: params[:query]).result(distinct: true)
    else
      Post.bookmarked_by_user(current_user)
    end
  end

  def set_data_video
    if params[:query].present?
      Video.bookmarked_by_user(current_user).ransack(title_or_description_cont: params[:query]).result(distinct: true)
    else
      Video.bookmarked_by_user(current_user)
    end
  end
end

app/views/dashboard/_all_video_card.html.erb
<% videos.each do |video| %>
  <div class="col-12 col-md-6">
    <div class="card mb-3 border" style="border: none">
      <%= link_to video_path(video), data:{turbo: false}, class: '' do %>
        <img src="<%= url_for(video.header_image) %>" class="card-img-top border-bottom"  style="height: 250px" alt="...">
      <% end %>
      <div class="card-body">
        <%= link_to video_path(video), data:{turbo: false}, class: 'text-decoration-none text-dark' do %>
          <h5 class="card-title single-line"><%= video.title %></h5>
        <% end %>
        <p class="card-text single-line"><%= video.description %></p>
      </div>
      <div class="card-header flex-column text-start">
        <div class="d-flex justify-content-between ">
          <div class="d-flex">
            <div class="d-flex justify-content-start align-items-center">
              <% if video.user.avatar_attachment %>
                <%= image_tag(video.user.avatar, alt: "User Avatar", class: "avatar-image rounded-circle") %>
              <% else %>
                <%= image_tag('user.jpg', alt: "User Avatar", class: "avatar-image rounded-circle") %>
              <% end %>
              <%= link_to "#{video.user.username}", profile_path(video.user),data:{turbo: false},class: "mx-1" %>
            </div>
            <% if current_user %>
              <% if video.user != current_user %>
                <%= render partial: 'profile/follow_button',locals: {user: video.user} %>
              <% end %>
            <% end %>
          </div>
          <%= render partial: 'videos/published_at',locals: {video: video} %>
        </div>
        <div class="mt-2">
          <strong>Tags:</strong>
          <% video.tags.each do |tag| %>
            <%= link_to "##{tag.name}", tag_path(tag), data:{turbo: false}, class: "title-post-card rounded-3 px-2 py-1"%>
          <% end %>
        </div>
      </div>
      <div class="card-footer text-muted d-flex justify-content-between" style="border: none; background-color: #EFEFEF;">
        <div>
          <span style="" class="text-dark mx-1">️🏅 <%= "#{pluralize(video.cached_weighted_like_score, "Point")}"%></span>
          <span style="" class="text-dark mx-1">💬 <%= "#{pluralize(video.vcomments.count, "Comment")}"%></span>
          <span style="" class="text-dark mx-1">👀 <%= "#{pluralize(video.total_views, "View")}"%></span>
        </div>
        <% if current_user %>
          <i class="fa-solid fa-bookmark <%= label_styles_bookmark(video, current_user) %>"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/_dashboard_menu.html.erb
<div class="d-flex flex-column px-3 py-3 rounded-3" style="background-color: #EFEFEF">
  <ul class="nav flex-column px-3">
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(page == "index") }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "Followers", dashboard_index_path, class: "nav-link text-black"%>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(page == "followee") }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "Following users", following_users_dashboard_index_path, class: "nav-link text-black" %>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(page == "tags") }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "Following tags", following_tags_dashboard_index_path, class: "nav-link text-black" %>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(page == "posts") }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "Posts bookmark", posts_bookmark_dashboard_index_path, class: "nav-link text-black" %>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(page == "videos") }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "Videos bookmark", videos_bookmark_dashboard_index_path, class: "nav-link text-black" %>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(page == "notifications") }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "Notifications", notifications_dashboard_index_path, class: "nav-link text-black" %>
      </div>
    <% end %>
  </ul>
</div>

app/views/dashboard/_tag.html.erb
<%= content_tag(:div, class: "col-lg-4 my-2 rounded", style: "height: 175px") do %>
  <div class="card mb-2 h-100" style="border: none;">
    <div class="card-header d-flex justify-content-between" style="border: none; background-color: #EFEFEF;">
      <%= link_to "@_#{tag.name}", tag_path(tag),data:{turbo: false},class: "mx-1" %>
      <%= "#{pluralize(Post.tagged_with(tag.name).count, "post")}" %>
    </div>
    <div class="card-body" style="background-color: #EFEFEF;">
      <p class="card-text"><%= tag.detail %></p>
    </div>
    <div class="card-footer text-muted d-flex align-items-center justify-content-between" style="border: none; background-color: #EFEFEF;">
      <div>
        <% if tag.tag_image.attached? %>
          <%= image_tag(tag.tag_image, alt: "#{tag.name}", class: "tag-image") %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/following_tags.html.erb
<div class="row justify-content-center">
  <h2>Dashboard</h2>
  <div class="row w-100 ">
    <div class="col-md-4">
      <%= render "dashboard/dashboard_menu", page: "tags" %>
    </div>
    <div class="col-md-8">
      <div class="d-flex row">
        <% if @tags.count > 0  %>
          <% @tags.each do |tag| %>
            <%= render "dashboard/tag", tag: tag %>
          <% end %>
        <% else %>
          <div class="d-flex justify-content-center align-items-center">
            <b>You don't have any tags! 😢😢😢</b>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/following_users.html.erb
<div class="row justify-content-center">
  <h2>Dashboard</h2>
  <div class="row w-100 ">
    <div class="col-md-4">
      <%= render "dashboard/dashboard_menu", page: "followee" %>
    </div>
    <div class="col-md-8">
      <div class="d-flex row">
        <% if @followee.count > 0  %>
          <% @followee.each do |user| %>
            <%= render "profile/user_card", user: user %>
          <% end %>
        <% else %>
          <div class="d-flex justify-content-center align-items-center">
            <b>You don't follow any users! 😢😢😢</b>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row justify-content-center">
  <h2>Dashboard</h2>
  <div class="row w-100 ">
    <div class="col-md-4">
      <%= render "dashboard/dashboard_menu", page: "index" %>
    </div>
    <div class="col-md-8">
      <div class="d-flex row">
        <% if @follower.count > 0  %>
          <% @follower.each do |user| %>
            <%= render "profile/user_card", user: user %>
          <% end %>
        <% else %>
          <div class="d-flex justify-content-center align-items-center">
            <b>You don't have any followers! 😢😢😢</b>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/notifications.html.erb
<div class="row justify-content-center">
  <h2>Dashboard</h2>
  <div class="row w-100 ">
    <div class="col-md-4">
      <%= render "dashboard/dashboard_menu", page: "notifications" %>
    </div>
    <div class="col-md-8">
      <% @notifications.each do |notification| %>
          <%= content_tag(:div) do %>
            <div class="card mb-2" style="border: none;">
              <div class="card-header d-flex justify-content-between align-items-center rounded-2" style="border: none; background-color: #EFEFEF;">
                <div>
                  <%= link_to "#{notification.as_read?? "☑️" : "🔔"} #{notification.content}",
                              view_object_path(notification),
                              data:{turbo: false},
                              style: if notification.healthy?
                                       notification.as_read? ? "color: #3887BE;" : "color: #E36414;"
                                     else
                                       "color: #BF3131;"
                                     end %>
                </div>
                <div>
                  <b>Created</b> <%= time_ago_in_words(notification.created_at) %> ago
                </div>
              </div>
            </div>
          <% end %>
      <% end %>
    </div>
  </div>
  <%= paginate @notifications, theme: 'bootstrap-5',
               pagination_class: "pagination-sm flex-wrap justify-content-end",
               nav_class: "d-inline-block col-12" %>
</div>

app/views/dashboard/posts_bookmark.html.erb
<div class="row justify-content-center">
  <h2>Dashboard</h2>
  <div class="row w-100 ">
    <div class="col-md-4">
      <%= render "dashboard/dashboard_menu", page: "posts" %>
    </div>
    <div class="col-md-8">
      <div class="d-flex justify-content-between align-items-center">
        <%= form_with(url: posts_bookmark_dashboard_index_path, method: :get, class: "form-inline my-2 my-lg-0 d-flex") do |form| %>
          <div class="position-relative d-flex">
            <%= hidden_field_tag 'index', params[:index].to_s %>
            <%= form.text_field :query,
                                class: "form-control mr-sm-2",
                                placeholder: "Search post bookmark ....", autocomplete: "off" %>
            <div class="d-flex">
              <%= form.submit "🔦", class: "btn btn-outline-primary mx-2" %>
            </div>
          </div>
        <% end %>
        <div class="d-flex">
          <button class="<%= params[:index] == "top" ? "btn btn-secondary mx-1 primary-color":"btn primary-bg mx-1"%>"><%= link_to "TOP", posts_bookmark_dashboard_index_path(index: "top"),class: "text-white"%></button>
          <button class="<%= params[:index] == "oldest" ? "btn btn-secondary mx-1 primary-color":"btn primary-bg mx-1"%>"><%= link_to "OLDEST", posts_bookmark_dashboard_index_path(index: "oldest"), class: "text-white"%></button>
          <button class="<%= params[:index] == "newest" ? "btn btn-secondary mx-1 primary-color":"btn primary-bg mx-1"%>"><%= link_to "NEWEST", posts_bookmark_dashboard_index_path(index: "newest"), class: "text-white"%></button>
        </div>
      </div>
      <div class="d-flex row mt-3">
        <%= turbo_frame_tag "posts_dashboard_#{dom_id(current_user)}", class: "row" do %>
          <%= render "posts/all_post_card", posts: @posts %>
        <% end %>
        <div id="load_more_button_posts_dashboard_<%= dom_id(current_user) %>" class="d-flex justify-content-center mb-5">
          <% if @pagy.next.present? %>
            <%= button_to "Load more", pagy_url_for(@pagy, @pagy.next), class: "btn btn-outline-primary btn-lg" %>
          <% else %>
          <span>
            <b>Nothing to show!!! 😁</b>
          </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/posts_bookmark.turbo_stream.erb
<%= turbo_stream.append "posts_dashboard_#{dom_id(current_user)}" do %>
  <%= render "posts/all_post_card", posts: @posts %>
<%end %>

<%= turbo_stream.update "load_more_button_posts_dashboard_#{dom_id(current_user)}" do %>
  <% if @pagy.next.present? %>
    <%= button_to "Load more", pagy_url_for(@pagy, @pagy.next), class: "btn btn-outline-primary btn-lg" %>
  <% else %>
    <span>
      <b>Nothing to show!!! 😁</b>
    </span>
  <% end %>
<% end %>

app/views/dashboard/videos_bookmark.html.erb
<div class="row justify-content-center">
  <h2>Dashboard</h2>
  <div class="row w-100 ">
    <div class="col-md-4">
      <%= render "dashboard/dashboard_menu", page: "videos" %>
    </div>
    <div class="col-md-8">
      <div class="d-flex justify-content-between align-items-center">
        <%= form_with(url: videos_bookmark_dashboard_index_path, method: :get, class: "form-inline my-2 my-lg-0 d-flex") do |form| %>
          <div class="position-relative d-flex">
            <%= hidden_field_tag 'index', params[:index].to_s %>
            <%= form.text_field :query,
                                class: "form-control mr-sm-2",
                                placeholder: "Search video bookmark ....", autocomplete: "off" %>
            <div class="d-flex">
              <%= form.submit "🔦", class: "btn btn-outline-primary mx-2" %>
            </div>
          </div>
        <% end %>
        <div class="d-flex">
          <button class="<%= params[:index] == "top" ? "btn btn-secondary mx-1 primary-color":"btn primary-bg mx-1"%>"><%= link_to "TOP", videos_bookmark_dashboard_index_path(index: "top"),class: "text-white"%></button>
          <button class="<%= params[:index] == "oldest" ? "btn btn-secondary mx-1 primary-color":"btn primary-bg mx-1"%>"><%= link_to "OLDEST", videos_bookmark_dashboard_index_path(index: "oldest"), class: "text-white"%></button>
          <button class="<%= params[:index] == "newest" ? "btn btn-secondary mx-1 primary-color":"btn primary-bg mx-1"%>"><%= link_to "NEWEST", videos_bookmark_dashboard_index_path(index: "newest"), class: "text-white"%></button>
        </div>
      </div>
      <div class="d-flex row mt-3">
        <%= turbo_frame_tag "videos_dashboard_#{dom_id(current_user)}", class: "row" do %>
          <%= render "dashboard/all_video_card", videos: @videos %>
        <% end %>
        <div id="load_more_button_videos_dashboard_<%= dom_id(current_user) %>" class="d-flex justify-content-center mb-5">
          <% if @pagy.next.present? %>
            <%= button_to "Load more", pagy_url_for(@pagy, @pagy.next), class: "btn btn-outline-primary btn-lg" %>
          <% else %>
          <span>
            <b>Nothing to show!!! 😁</b>
          </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/videos_bookmark.turbo_stream.erb
<%= turbo_stream.append "videos_dashboard_#{dom_id(current_user)}" do %>
  <%= render "dashboard/all_video_card", videos: @videos %>
<%end %>

<%= turbo_stream.update "load_more_button_videos_dashboard_#{dom_id(current_user)}" do %>
  <% if @pagy.next.present? %>
    <%= button_to "Load more", pagy_url_for(@pagy, @pagy.next), class: "btn btn-outline-primary btn-lg" %>
  <% else %>
    <span>
      <b>Nothing to show!!! 😁</b>
    </span>
  <% end %>
<% end %>