config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  # get '/:locale' => 'home#index'
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # action home page
  get '/posts', to: "home#index_show_post", as: 'posts_index'
  post '/posts', to: "home#index_show_post", as: 'get_post_index_pagy'
  get '/videos', to: "home#index_show_video", as: 'videos_index'
  post '/videos', to: "home#index_show_video", as: 'get_video_index_pagy'

  # action admin
  namespace 'admin' do
    get :index_ban_user, to: "users#index_ban_user"
    resources :users do
      member do
        get :action_ban_user
        get :action_unban_user
        post :ban_user
        post :unban_user
      end
    end
    resources :posts do
      member do
        get :action_accept_post
        get :action_refuse_post
        post :accept_post
        post :refuse_post
      end
    end
    resources :videos do
      member do
        get :action_accept_video
        get :action_refuse_video
        post :accept_video
        post :refuse_video
      end
    end
  end

  # action user
  scope '/users' do
    resources :posts do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_post
      end
      resources :elements
      resources :comments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
    resources :videos do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_video
      end
      resources :vcomments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
  end

  resources :chats do
    resources :messages
  end
  resources :tags do
    member do
      post :show, as: 'get_posts_tag_index_pagy'
      get :show_video
      post :show_video, as: 'get_videos_tag_index_pagy'
      post :added_tag
    end
  end
  resources :profile, only:  [:show] do
    member do
      post :follow
      delete :unfollow
      get :action_report_user
      post :report_user
    end
  end
  resources :dashboard do
    collection do
      # get :user_followers
      get :following_tags
      get :following_users
      get :posts_bookmark
      post :posts_bookmark, as: 'get_posts_dashboard_pagy'
      get :videos_bookmark
      post :videos_bookmark, as: 'get_videos_dashboard_pagy'
      get :notifications
    end
  end

  # action search
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get 'search', to: 'search#search_all', as: 'search_all'
  get 'show_all_user_search', to: 'search#show_all_user_search', as: :show_all_user_search

  # View Object Notification
  get '/notification/:id', to: 'notification#view_object', as: 'view_object'
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_one_attached :header_image
  has_many :elements, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tags
  has_many :notifications, as: :object, dependent: :destroy

  acts_as_votable
  acts_as_taggable_on :tags

  enum status: { un_status: 0, in_queue: 1, accept: 2, refuse: 3 }

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true
  validates :header_image, presence: true

  def bookmark!(user)
    if user.voted_up_on? self, vote_scope: "bookmark"
      unvote_by user, vote_scope: "bookmark"
    else
      upvote_by user, vote_scope: "bookmark"
    end
  end

  def upvote!(user)
    if user.voted_up_on? self, vote_scope: "like"
      unvote_by user, vote_scope: "like"
    else
      upvote_by user, vote_scope: "like"
    end
  end

  def downvote!(user)
    if user.voted_down_on? self, vote_scope: "like"
      unvote_by user, vote_scope: "like"
    else
      downvote_by user, vote_scope: "like"
    end
  end

  def self.bookmarked_by_user(user)
    joins(:votes_for)
      .where(votes: { voter_id: user.id, vote_scope: 'bookmark', votable_type: 'Post' })
  end

  def self.ransackable_attributes(auth_object = nil)
    ["already_published", "cached_scoped_bookmark_votes_down", "cached_scoped_bookmark_votes_score", "cached_scoped_bookmark_votes_total", "cached_scoped_bookmark_votes_up", "cached_scoped_like_votes_down", "cached_scoped_like_votes_score", "cached_scoped_like_votes_total", "cached_scoped_like_votes_up", "cached_weighted_bookmark_average", "cached_weighted_bookmark_score", "cached_weighted_bookmark_total", "cached_weighted_like_average", "cached_weighted_like_score", "cached_weighted_like_total", "created_at", "description", "id", "published", "published_at", "title", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["base_tags", "commented_users", "comments", "elements", "header_image_attachment", "header_image_blob", "notifications", "tag_taggings", "taggings", "tags", "user", "votes_for"]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :set_data
  def suggestions
    @users = search_for_users
    @posts = search_for_posts
    @videos = search_for_videos

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:
                 turbo_stream.update('suggestions',
                                     partial: 'search/suggestions',
                                     locals: {
                                       users: @users,
                                       posts: @posts,
                                       videos: @videos
                                     })
      end
    end
  end
  def search_all
    if params[:query].blank?
      @users =  @search_blank_users
      @posts = @search_blank_posts
      @videos = @search_blank_videos
    else
      @users = @set_users
      @posts = @set_posts
      @videos = @set_videos
    end

  end

  def show_all_user_search
    if params[:query].blank?
      @users =  User.page(params[:page]).per(12)
    else
      @users = @set_users.page(params[:page]).per(12)
    end
  end

  private
  def set_data


    # @set_users = User.where('first_name LIKE ? OR last_name = ?', "%#{params[:query]}%", "%#{params[:query]}%")
    @q_user = User.ransack(first_name_or_last_name_cont: params[:query])
    @q_post = Post.ransack(title_or_description_cont: params[:query])
    @q_video = Video.ransack(title_or_description_cont: params[:query])
    @set_users = @q_user.result(distinct: true)
    if params[:tag_ids].present?
      @set_posts = @q_post.result(distinct: true).joins(:tags).where(tags: { id: params[:tag_ids] }).where(published: true).distinct
      @set_videos = @q_video.result(distinct: true).joins(:tags).where(tags: { id: params[:tag_ids] }).where(published: true).distinct
      @search_blank_users = User.joins(:tags).where(tags: { id: params[:tag_ids] }).limit(6)
      @search_blank_posts = Post.joins(:tags).where(tags: { id: params[:tag_ids] }).limit(6)
      @search_blank_videos = Video.joins(:tags).where(tags: { id: params[:tag_ids] }).limit(6)
    else
      @set_posts = @q_post.result(distinct: true).where(published: true).distinct
      @set_videos = @q_video.result(distinct: true).where(published: true).distinct
      @search_blank_users = User.limit(6)
      @search_blank_posts = Post.limit(6)
      @search_blank_videos = Video.limit(6)
    end

  end
  def search_params
    params.permit(:term)
  end
  def search_for_users
    if params[:query].blank?
      User.joins(:tags).where(tags: { id: params[:tag_ids] }).limit(3)
    else
      @set_users.limit(3)
    end
  end

  def search_for_posts
    if params[:query].blank?
      Post.joins(:tags).where(tags: { id: params[:tag_ids] }).limit(3)
    else
      @set_posts.limit(3)
    end
  end

  def search_for_videos
    if params[:query].blank?
      Video.joins(:tags).where(tags: { id: params[:tag_ids] }).limit(3)
    else
      @set_videos.limit(3)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.erb
<%= form_with(url: search_all_path, method: :get, class: "form-inline my-2 my-lg-0 d-flex", data: {
  controller: "search",
  action: "keyup->search#suggestions",
  suggestions_url: search_suggestions_path,
}) do |form| %>
  <div class="position-relative d-flex" style="width: 500px">
    <%= form.text_field :query,
                        value: (params[:query] if params[:query].present?),
                        data: {
                          search_target: "input",
                          action: "blur->search#hideSuggestions",
                        },
                        class: "form-control mr-sm-2",
                        placeholder: "Type something....", autocomplete: "off" %>
    <a href="#" class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" data-target="search.total_tags">
      <%= "Total tags: #{params[:tag_ids].present? ? params[:tag_ids].count : 0}" %>
    </a>
    <ul class="dropdown-menu" style="left: -20%; width: 540px" aria-labelledby="dropdownMenuButton1">
      <div class="d-flex w-100" >
        <div class="col-md-12">
          <select id="choices-multiple-remove-button"
                  data-search-target="list_tags"
                  placeholder="Select upto 5 tags"
                  multiple name="tag_ids[]"
                  data-action="change->search#selectChanged">
            <% Tag.all.each do |tag| %>
              <%= content_tag(:option,value: tag.id, selected: (params[:tag_ids].include?(tag.id.to_s) if params[:tag_ids].present?)) do %>
                <%= tag.name %>
              <% end %>
            <% end %>
          </select>
        </div>
      </div>
    </ul>
    <div class="d-flex">
      <%= form.submit "🔎", class: "button-search btn btn-outline-light mx-2" %>
    </div>
    <div id="suggestions" class="position-absolute w-100 top-100"
         data-search-target="suggestions" data-action="mousedown->search#childClicked">
      <%= render partial: "search/suggestions", locals: { users: users, posts: posts ,videos: videos} %>
    </div>
  </div>
<% end %>

app/views/search/_search_post.html.erb
<% if posts.count > 0 %>
  <h3 class="col-12">Posts Result</h3>
  <%= render "posts/all_post_card", posts: posts %>
<% else %>
  <h3 class="col-12">Nothing posts to show!!!</h3>
<% end %>

app/views/search/_search_user.html.erb
<% if users.count > 0 %>
  <h3 class="col-12">Users Result</h3>
  <% users.each do |user| %>
    <%= render "profile/user_card", user: user %>
  <% end %>
<% else %>
  <h3 class="col-12">Nothing users to show!!!</h3>
<% end %>

app/views/search/_search_video.html.erb
<% if videos.count > 0 %>
  <h3 class="col-12">Videos Result</h3>
  <%= render "videos/all_video_card", videos: videos %>
<% else %>
  <h3 class="col-12">Nothing videos to show!!!</h3>
<% end %>

app/views/search/_suggestions.html.erb
<div class="position-absolute rounded overflow-hidden suggestion" style="width: 83%">
  <% if users.any? || posts.any? || videos.any? %>
    <% if users.any? %>
      <h5>Users suggest</h5>
      <% users.each do |user| %>
        <div class="p-2  d-flex align-items-start border">
          <% if user.avatar.attached? %>
            <%= image_tag(user.avatar, alt: "#{user.username}", class: "avatar-image mx-1", id: "avatarUserHeader") %>
          <% else %>
            <%= image_tag("user.jpg", alt: "#{user.username}", class: "avatar-image mx-1", id: "avatarUserHeader") %>
          <% end %>
          <%= link_to user.username, profile_path(user),class: "suggestion-title" %>
        </div>
      <% end %>
      <hr/>
    <% end %>
    <% if posts.any? %>
      <h5>Posts suggest</h5>
      <% posts.each do |post| %>
        <div class="p-2  d-flex flex-column align-items-start border">
          <div class="d-flex">
            <%= image_tag(post.header_image, alt: "#{post.title}", class: "avatar-image mx-1", id: "avatarUserHeader") %>
            <%= link_to post.title, post_path(post),class: "suggestion-title" %>
          </div>
          <div>
            <% post.tags.each do |tag| %>
              <%= link_to "##{tag.name}", tag_path(tag), data:{turbo: false}, class: "title-post-card rounded-3 px-2 py-1"%>
            <% end %>
          </div>
        </div>
      <% end %>
      <hr/>
    <% end %>
    <% if videos.any? %>
      <h5>Videos suggest</h5>
      <% videos.each do |video| %>
        <div class="p-2  d-flex flex-column align-items-start border">
          <div class="d-flex">
            <%= image_tag(video.header_image, alt: "#{video.title}", class: "avatar-image mx-1", id: "avatarUserHeader") %>
            <%= link_to video.title, video_path(video),class: "suggestion-title" %>
          </div>
          <div>
            <% video.tags.each do |tag| %>
              <%= link_to "##{tag.name}", tag_path(tag), data:{turbo: false}, class: "title-post-card rounded-3 px-2 py-1"%>
            <% end %>
          </div>
        </div>
      <% end %>
      <hr/>
    <% end %>
  <% else %>
    <b class="mx-2 my-2">
      Nothing to found!
    </b>
  <% end %>

</div>

app/views/search/search_all.html.erb
<h1>Search Page</h1>
<main role="main" class="col-lg-12 px-md-4 mx-auto pt-3">
  <div class="row justify-content-start">
    <%= render "search/search_user", users: @users %>
    <hr/>
    <%= render "search/search_post", posts: @posts %>
    <hr/>
    <%= render "search/search_video", videos: @videos %>
  </div>
</main>

app/views/search/show_all_user_search.html.erb
<% @users.each do |user| %>
  <%= render "profile/user_card", user: user %>
<% end %>
<%= paginate @users, theme: 'bootstrap-5',
             pagination_class: "pagination-sm flex-wrap justify-content-center",
             nav_class: "d-inline-block col-12" %>