config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  # get '/:locale' => 'home#index'
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # action home page
  get '/posts', to: "home#index_show_post", as: 'posts_index'
  post '/posts', to: "home#index_show_post", as: 'get_post_index_pagy'
  get '/videos', to: "home#index_show_video", as: 'videos_index'
  post '/videos', to: "home#index_show_video", as: 'get_video_index_pagy'

  # action admin
  namespace 'admin' do
    get :index_ban_user, to: "users#index_ban_user"
    resources :users do
      member do
        get :action_ban_user
        get :action_unban_user
        post :ban_user
        post :unban_user
      end
    end
    resources :posts do
      member do
        get :action_accept_post
        get :action_refuse_post
        post :accept_post
        post :refuse_post
      end
    end
    resources :videos do
      member do
        get :action_accept_video
        get :action_refuse_video
        post :accept_video
        post :refuse_video
      end
    end
  end

  # action user
  scope '/users' do
    resources :posts do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_post
      end
      resources :elements
      resources :comments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
    resources :videos do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_video
      end
      resources :vcomments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
  end

  resources :chats do
    resources :messages
  end
  resources :tags do
    member do
      post :show, as: 'get_posts_tag_index_pagy'
      get :show_video
      post :show_video, as: 'get_videos_tag_index_pagy'
      post :added_tag
    end
  end
  resources :profile, only:  [:show] do
    member do
      post :follow
      delete :unfollow
      get :action_report_user
      post :report_user
    end
  end
  resources :dashboard do
    collection do
      # get :user_followers
      get :following_tags
      get :following_users
      get :posts_bookmark
      post :posts_bookmark, as: 'get_posts_dashboard_pagy'
      get :videos_bookmark
      post :videos_bookmark, as: 'get_videos_dashboard_pagy'
      get :notifications
    end
  end

  # action search
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get 'search', to: 'search#search_all', as: 'search_all'
  get 'show_all_user_search', to: 'search#show_all_user_search', as: :show_all_user_search

  # View Object Notification
  get '/notification/:id', to: 'notification#view_object', as: 'view_object'
end

app/models/video.rb
class Video < ApplicationRecord
  
  belongs_to :user
  has_one_attached :header_image, dependent: :destroy
  has_one_attached :video, dependent: :destroy
  has_many :vcomments, dependent: :destroy
  has_many :tags
  has_many :notifications, as: :object, dependent: :destroy

  acts_as_votable
  acts_as_taggable_on :tags

  enum status: { un_status: 0, in_queue: 1, accept: 2, refuse: 3 }

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :header_image, presence: true
  validates :video, presence: true

  def bookmark!(user)
    if user.voted_up_on? self, vote_scope: "bookmark"
      unvote_by user, vote_scope: "bookmark"
    else
      upvote_by user, vote_scope: "bookmark"
    end
  end

  def upvote!(user)
    if user.voted_up_on? self, vote_scope: "like"
      unvote_by user, vote_scope: "like"
    else
      upvote_by user, vote_scope: "like"
    end
  end

  def downvote!(user)
    if user.voted_down_on? self, vote_scope: "like"
      unvote_by user, vote_scope: "like"
    else
      downvote_by user, vote_scope: "like"
    end
  end

  def self.bookmarked_by_user(user)
    joins(:votes_for)
      .where(votes: { voter_id: user.id, vote_scope: 'bookmark', votable_type: 'Video' })
  end

  def self.ransackable_attributes(auth_object = nil)
    ["already_published", "cached_scoped_bookmark_votes_down", "cached_scoped_bookmark_votes_score", "cached_scoped_bookmark_votes_total", "cached_scoped_bookmark_votes_up", "cached_scoped_like_votes_down", "cached_scoped_like_votes_score", "cached_scoped_like_votes_total", "cached_scoped_like_votes_up", "cached_weighted_bookmark_average", "cached_weighted_bookmark_score", "cached_weighted_bookmark_total", "cached_weighted_like_average", "cached_weighted_like_score", "cached_weighted_like_total", "created_at", "description", "id", "published", "published_at", "title", "total_views", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["base_tags", "header_image_attachment", "header_image_blob", "notifications", "tag_taggings", "taggings", "tags", "user", "vcomments", "video_attachment", "video_blob", "votes_for"]
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin

  def index
    @videos = Video.where(status: :in_queue).order(created_at: :desc).page(params[:page]).per(15)
  end

  def action_accept_video
    @video = Video.find(params[:id])
  end

  def action_refuse_video
    @video = Video.find(params[:id])
  end

  def accept_video
    ActiveRecord::Base.transaction do
      @video = Video.find(params[:id])
      @video.update_columns(status: 2)
      Notification.create(
        sender: current_user,
        receiver: @video.user,
        object: @video,
        as_read: false,
        content: "Your video name #{@video.title} successfully accept!"
      )
      @video.user.follower.each do |user|
        message = "User #{@video.user.username} just creating a new videos!"
        Notification.create(
          sender: @video.user,
          receiver: user,
          object: @video,
          as_read: false,
          content: message
        )
      end
    end
    respond_to do |format|
      format.html { redirect_to admin_videos_url, :notice => 'Video was successfully accept.'  }
    end
  end

  def refuse_video
    ActiveRecord::Base.transaction do
      @video = Video.find(params[:id])
      @video.update_columns(status: 3,published: false, published_at: nil)
      Notification.create(
        sender: current_user,
        receiver: @video.user,
        object: @video,
        as_read: false,
        content: "Your video name #{@video.title} was refuse!",
        status: 1
      )
    end

    respond_to do |format|
      format.html { redirect_to admin_videos_url, :notice => 'Video was successfully refuse.'  }
    end
  end

  private

  def authorize_admin
    unless current_user&.admin? || current_user&.censor?
      redirect_to root_path, alert: 'Access denied.'
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!, only: %i[ index new edit create update destroy vote bookmark]
  before_action :set_video, only: %i[ show edit update destroy publish unpublish vote bookmark action_delete_video]
  before_action :check_video_ownership, only: [:edit, :update, :destroy]

  # GET /photos or /photos.json
  def index
    @videos = current_user.videos.page(params[:page]).per(8)
  end

  # GET /photos/1 or /photos/1.json
  def show
    if current_user
      @video.increment!(:total_views)
    end
  end

  # GET /photos/new
  def new
    @video = current_user.videos.build
  end

  # GET /photos/1/edit
  def edit

  end

  # POST /photos or /photos.json
  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to edit_video_path(@video), notice: "Video was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html {
          flash[:notice] = 'Video was successfully updated.'
          redirect_to edit_video_path(@video)
        }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
    end
  end

  def publish
    if @video.accept?
      @video.update(published: true, published_at: Time.now)
      respond_to do |format|
        format.html { redirect_to edit_video_url(@video), notice: "Your video was successfully published." }
      end
    else
      @video.update(published: true,status: 1, published_at: Time.now)
      @video_status = @video.status
      User.admin_and_censor.each do |user|
        message = "Need to check a video #{@video.user.username} just published!!!"
        create_notification_for_censor(@video.user,user,@video,message)
      end
      respond_to do |format|
        format.html { redirect_to edit_video_url(@video), notice: "Your video need to check before publish!" }
      end
    end


  end

  def unpublish
    @video.update(published: false, published_at: nil)

    respond_to do |format|
      format.html { redirect_to edit_video_url(@video), notice: "Your video was successfully unpublished." }
    end
  end

  def bookmark
    @video.bookmark!(current_user)
    respond_to do |format|
      format.html do
        redirect_to @video
      end
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@video, partial: "videos/video", locals: {video: @video})
      end
    end
  end

  def vote
    case params[:type]
    when 'upvote'
      @video.upvote!(current_user)
    when 'downvote'
      @video.downvote!(current_user)
    else
      return redirect_to request.url, alert: "No such vote type"
    end
    respond_to do |format|
      format.html do
        redirect_to @video
      end
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@video, partial: "videos/video", locals: {video: @video})
      end
    end
  end

  def action_delete_video
  end

  private

  def set_video
    @video = Video.find(params[:id])
  end


  def video_params
    params.require(:video).permit(:title, :description, :header_image, :video, :tag_list)
  end
  
  def check_video_ownership
    video = Video.find_by(id: params[:id])
    if video && video.user_id == current_user.id
    else
      redirect_to root_path, alert: 'Access denied.'
    end
  end

  def update_action_publish
    private_target = ".#{helpers.dom_id(@video)}_publish_video"
    turbo_stream.replace_all(private_target,
                             partial: 'videos/publisher_button',
                             locals: {
                               video: @video
                             })
  end

  def update_published_at
    private_target = ".#{helpers.dom_id(@video)}_published_at"
    turbo_stream.replace_all(private_target,
                             partial: 'videos/published_at',
                             locals: {
                               video: @video
                             })
  end

  def create_notification_for_censor(sender,receiver,video,message)
    # Tạo Notification cho comment
    Notification.create(
      sender: sender,
      receiver: receiver,
      object: video,
      as_read: false,
      content: message
    )
  end
end

app/helpers/videos_helper.rb
module VideosHelper

  def video_label_styles(video, user, type)
    case type
    when 'upvote'
      if user.voted_up_on? video, vote_scope: "like"
        "fa-bounce text-info"
      else
        "text-dark"
      end
    when 'downvote'
      if user.voted_down_on? video, vote_scope: "like"
        "fa-bounce text-danger"
      else
        "text-dark"
      end
    end
  end

  def video_score_type(user, video)
    if user.voted_up_on? video, vote_scope: "like"
      "text-info"
    elsif user.voted_down_on? video, vote_scope: "like"
      "text-danger"
    else
      "text-dark"
    end
  end

  def video_label_styles_bookmark(video, user)
    if user.voted_up_on? video, vote_scope: "bookmark"
      "text-warning"
    else
      "text-dark"
    end
  end
end

app/views/videos/_all_video_card.html.erb
<% videos.each do |video| %>
  <div class="col-12 col-md-4">
    <div class="card mb-3 border" style="border: none">
      <%= link_to video_path(video), data:{turbo: false}, class: '' do %>
        <img src="<%= url_for(video.header_image) %>" class="card-img-top border-bottom"  style="height: 250px" alt="...">
      <% end %>
      <div class="card-body">
        <%= link_to video_path(video), data:{turbo: false}, class: 'text-decoration-none text-dark' do %>
          <h5 class="card-title single-line"><%= video.title %></h5>
        <% end %>
        <p class="card-text single-line"><%= video.description %></p>
      </div>
      <div class="card-header flex-column text-start">
        <div class="d-flex justify-content-between ">
          <div class="d-flex">
            <div class="d-flex justify-content-start align-items-center">
              <% if video.user.avatar_attachment %>
                <%= image_tag(video.user.avatar, alt: "User Avatar", class: "avatar-image rounded-circle") %>
              <% else %>
                <%= image_tag('user.jpg', alt: "User Avatar", class: "avatar-image rounded-circle") %>
              <% end %>
              <%= link_to "#{video.user.username}", profile_path(video.user),data:{turbo: false},class: "mx-1" %>
            </div>
            <% if current_user %>
              <% if video.user != current_user %>
                <%= render partial: 'profile/follow_button',locals: {user: video.user} %>
              <% end %>
            <% end %>
          </div>
          <%= render partial: 'videos/published_at',locals: {video: video} %>
        </div>
        <div class="mt-2">
          <strong>Tags:</strong>
          <% video.tags.each do |tag| %>
            <%= link_to "##{tag.name}", tag_path(tag), data:{turbo: false}, class: "title-post-card rounded-3 px-2 py-1"%>
          <% end %>
        </div>
      </div>
      <div class="card-footer text-muted d-flex justify-content-between" style="border: none; background-color: #EFEFEF;">
        <div>
          <span style="" class="text-dark mx-1">️🏅 <%= "#{pluralize(video.cached_weighted_like_score, "Point")}"%></span>
          <span style="" class="text-dark mx-1">💬 <%= "#{pluralize(video.vcomments.count, "Comment")}"%></span>
          <span style="" class="text-dark mx-1">👀 <%= "#{pluralize(video.total_views, "View")}"%></span>
        </div>
        <% if current_user %>
          <i class="fa-solid fa-bookmark <%= label_styles_bookmark(video, current_user) %>"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/videos/_form.html.erb
<%= form_with(model: video, class: "mb-2") do |form| %>
  <% if video.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% video.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-3 border border-2 rounded-2 mb-2">
      <div class="form-outline mb-4 w-100">
        <%= form.label :title %>
        <%= form.text_field :title,class: "form-control form-control-lg" %>
      </div>
      <div class="form-outline mb-4 w-100">
        <%= form.label :description %>
        <%= form.text_area :description,class: "form-control form-control-lg" %>
      </div>
      <div class="form-outline mb-4 w-100">
        <%= form.label :tag_list, "Tags (separated by commas)" %><br />
        <%= form.text_field :tag_list, value: video.tag_list.join(","), class: 'form-control' %>
      </div>
      <div class="mb-2 mt-2">
        <div class="profile-img" data-controller="upload-image">
          <% if video.header_image.attached? %>
            <div class="avatar">
              <%= image_tag(video.header_image, alt: "#{video.title}", class: "photo-image", id: "imgPhoto",style: 'width: 100%;height:150px',data: { target: 'upload-image.avatar'}) %>
            </div>
          <%else %>
            <div class="avatar">
              <%= image_tag('image.jpg', class: "photo-image", id: "imgPhoto",style: 'width: 100%;height:150px',data: { target: 'upload-image.avatar'}) %>
            </div>
          <% end %>
          <%= form.label :header_image,"Change header photo", class: "col-8 col-form-label label-avatar" %>
          <%= form.file_field :header_image,
                              class: "d-none",
                              placeholder: 'Update picture',
                              data:{action: 'change->upload-image#handleChange'},
                              accept: 'image/*',
                              direct_upload: true %>
        </div>
      </div>
    </div>
    <div class="col-9">
      <div class="">
        <% if video.video.attached? %>
          <div class="video">
            <%= video_tag url_for(video.video), style: 'width:100%', controls: true, autoplay: true,loop: true %>
          </div>
          <%= form.file_field :video, accept: 'video/*' %>
        <% else %>
          <h3>Add your video</h3>
          <%= form.file_field :video, accept: 'video/*' %>
        <% end %>

      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>


app/views/videos/_published_at.html.erb
<%= turbo_frame_tag "#{dom_id(video)}_published_at" ,class: "#{dom_id(video)}_published_at" do %>
  <% if video.published? %>
    <b>Published</b> <%= time_ago_in_words(video.published_at) %> ago
  <% else %>
    <b>Unpublished</b>
  <% end %>
<% end %>

app/views/videos/_publisher_button.html.erb
<%= turbo_frame_tag "#{dom_id(video)}_publish_video" ,class: "#{dom_id(video)}_publish_video" do %>
  <% if video.published? %>
    <%= link_to "Unpublish", unpublish_video_path(id: video.id), class: "btn btn-warning btn-block w-100",data: { turbo_method: :post } %>
  <% else %>
    <%= link_to "Publish", publish_video_path(id: video.id), class: "btn btn-secondary btn-block w-100",data: { turbo_method: :post }%>
  <% end %>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
  <div class="row">
    <div class="col-md-1">
      <% if current_user %>
        <%= render 'votable' , user: current_user, video: video %>
      <% else %>
        <%= render 'votable_guest',video: video%>
      <% end %>
    </div>
    <div class="col-md-11">
      <div class="card mb-3" style="border: none">
        <div class="card-header d-flex justify-content-between text-end">
          <div class="d-flex">
            <div class="d-flex justify-content-start align-items-center">
              <% if video.user.avatar_attachment %>
                <%= image_tag(video.user.avatar, alt: "User Avatar", class: "avatar-image rounded-circle") %>
              <% else %>
                <%= image_tag('user.jpg', alt: "User Avatar", class: "avatar-image rounded-circle") %>
              <% end %>
              <%= link_to "#{video.user.username}", profile_path(video.user),data:{turbo: false},class: "mx-1" %>
            </div>
            <% if current_user %>
              <% if video.user != current_user %>
                <%= render partial: 'profile/follow_button',locals: {user: video.user} %>
              <% end %>
            <% end %>
          </div>
          <%= render partial: 'videos/published_at',locals: {video: video} %>
        </div>
        <div class="card-body">
          <div class="video">
            <%= video_tag url_for(video.video), style: 'width:100%', controls: true, autoplay: true,loop: true %>
          </div>
        </div>
      </div>
      <div class="card mb-5" style="border: none">
        <div class="card-body pt-2">
          <h5 class="card-title"><%= video.title %></h5>
          <p class="card-text"><%= video.description %></p>
        </div>
        <div class="card-footer pt-3 pb-3">
          <strong>Tags:</strong>
          <% video.tags.each do |tag| %>
            <%= link_to "##{tag.name}", tag_path(tag), data:{turbo: false}, class: "title-post-card rounded-3 px-2 py-1"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/videos/_video_card.html.erb
<div class="row row-cols-4 d-flex align-items-center">
  <% videos.each do |video| %>
    <div class="col col-6 col-md-3 my-2 rounded float-left profile-card-img">
      <div class="profile-photo-card card border-0 align-items-center justify-content-center">
        <%= image_tag(video.header_image, alt: "#{video.title}", class: "profile-photo w-100 card-img-top", id: "avatar",style: 'height:300px;width:300px') %>
        <div class="card-body">
          <p class="card-text"><%= video.title %></p>
        </div>
        <% unless video.published? %>
          <i class="border-white fa-solid fa-lock private-photo"></i>
        <% end %>
        <%= link_to "Edit",edit_video_path(video),class: "card-link-edit btn btn-lg btn-primary" %>
        <%= link_to "View", video_path(video),class: "card-link-view btn btn-lg btn-primary" %>
      </div>
    </div>

  <% end %>
  <%= paginate videos, theme: 'bootstrap-5',
               pagination_class: "pagination-sm flex-wrap justify-content-center",
               nav_class: "d-inline-block col-12" %>
</div>

app/views/videos/_votable.html.erb
<div class="d-flex flex-column justify-content-center">
  <%= link_to vote_video_path(video, type: :upvote),data: { turbo_method: :patch }, class: "item-votable" do %>
    <i class="fa-solid fa-angles-up <%= video_label_styles(video, user, "upvote") %>"></i>
  <% end %>
  <span style="" class="item-votable <%= video_score_type(user,video) %>"><%= video.cached_weighted_like_score %></span>
  <%= link_to vote_video_path(video, type: :downvote),data: { turbo_method: :patch }, class: "item-votable" do %>
    <i class="fa-solid fa-angles-down <%= video_label_styles(video, user, "downvote") %>"></i>
  <% end %>
  <%= link_to bookmark_video_path(video, type: :downvote),data: { turbo_method: :patch }, class: "item-votable" do %>
    <i class="fa-solid fa-bookmark <%= video_label_styles_bookmark(video, user) %>"></i>
  <% end %>
</div>

app/views/videos/_votable_guest.html.erb
<div class="d-flex flex-column justify-content-center">
  <%= link_to vote_video_path(video, type: :upvote),data: { turbo_method: :patch }, class: "item-votable text-dark" do %>
    <i class="fa-solid fa-angles-up"></i>
  <% end %>
  <span style="" class="item-votable text-dark"><%= video.cached_weighted_like_score %></span>
  <%= link_to vote_video_path(video, type: :downvote),data: { turbo_method: :patch }, class: "item-votable text-dark" do %>
    <i class="fa-solid fa-angles-down"></i>
  <% end %>
  <%= link_to bookmark_video_path(video, type: :downvote),data: { turbo_method: :patch }, class: "item-votable text-dark" do %>
    <i class="fa-solid fa-marker"></i>
  <% end %>
</div>

app/views/videos/action_delete_video.html.erb
<%= render "layouts/remote_modal" do %>
  <div class="modal-header">
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body d-flex flex-column align-items-center justify-content-center">
    <h1>Delete this video?</h1>
    <div class="d-flex justify-content-between w-100">
      <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">No</button>
      <%= button_to "Yes", video_path(@video), method: :delete, class: "btn btn-danger w-100 mt-2"%>
    </div>
  </div>
  <div class="modal-footer"></div>
<% end %>

app/views/videos/edit.html.erb
<div class="d-flex mb-2 justify-content-between">
  <%= link_to "Back to videos", videos_path,class: "btn btn-secondary" %>
  <div class="d-flex">
    <% if @video.published? %>
      <%= button_to "Unpublish", unpublish_video_path(@video), class: "btn btn-warning btn-block mx-2"%>
    <% else %>
      <%= button_to "Publish", publish_video_path(@video), class: "btn btn-primary btn-block mx-2"%>
    <% end %>
    <%= link_to "Delete", action_delete_video_video_path(@video),
                class: "btn btn-danger", data: { turbo_frame: "remote_modal" } %>
  </div>

</div>
<hr/>
<%= render "form", video: @video %>

app/views/videos/index.html.erb
<div class="d-flex justify-content-between mb-2">
  <h2>My Videos</h2>
  <%= link_to "New video", new_video_path, class: 'btn btn-primary' %>
</div>

<% if @videos.count > 0 %>
  <% @videos.each do |video| %>
    <div class="col-12 col-md-4">
      <div class="card mb-3 border" style="border: none">
        <%= link_to edit_video_path(video), data:{turbo: false}, class: '' do %>
          <img src="<%= url_for(video.header_image) %>" class="card-img-top border-bottom"  style="height: 250px" alt="...">
        <% end %>
        <div class="card-body">
          <%= link_to edit_video_path(video), data:{turbo: false}, class: 'text-decoration-none text-dark' do %>
            <h5 class="card-title single-line"><%= video.title %></h5>
          <% end %>
          <p class="card-text single-line"><%= video.description %></p>
        </div>
        <div class="card-header flex-column text-start">
          <div class="d-flex justify-content-between ">
            <div class="d-flex">
              <div class="d-flex justify-content-start align-items-center">
                <% if video.user.avatar_attachment %>
                  <%= image_tag(video.user.avatar, alt: "User Avatar", class: "avatar-image rounded-circle") %>
                <% else %>
                  <%= image_tag('user.jpg', alt: "User Avatar", class: "avatar-image rounded-circle") %>
                <% end %>
                <%= link_to "#{video.user.username}", profile_path(video.user),data:{turbo: false},class: "mx-1" %>
              </div>
              <% if current_user %>
                <% if video.user != current_user %>
                  <%= render partial: 'profile/follow_button',locals: {user: video.user} %>
                <% end %>
              <% end %>
            </div>
            <%= render partial: 'videos/published_at',locals: {video: video} %>
          </div>
          <div class="mt-2">
            <strong>Tags:</strong>
            <% video.tags.each do |tag| %>
              <%= link_to "##{tag.name}", tag_path(tag), data:{turbo: false}, class: "title-post-card rounded-3 px-2 py-1"%>
            <% end %>
          </div>
        </div>
        <div class="card-footer text-muted d-flex justify-content-between" style="border: none; background-color: #EFEFEF;">
          <div>
            <span style="" class="text-dark mx-1">️🏅 <%= "#{pluralize(video.cached_weighted_like_score, "Point")}"%></span>
            <span style="" class="text-dark mx-1">💬 <%= "#{pluralize(video.vcomments.count, "Comment")}"%></span>
            <span style="" class="text-dark mx-1">👀 <%= "#{pluralize(video.total_views, "View")}"%></span>
          </div>
          <% if current_user %>
            <i class="fa-solid fa-bookmark <%= label_styles_bookmark(video, current_user) %>"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <span class="d-flex justify-content-center">
    <b>You don't have any videos!!! 😁</b>
  </span>
<% end %>

app/views/videos/new.html.erb
<div class="d-flex mb-2 justify-content-between">
  <h4>New Video</h4>
  <%= link_to "Back to videos", videos_path,class: "btn btn-secondary"%>
</div>

<hr/>
<%= render "form", video: @video %>

<br>


app/views/videos/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render @video %>
  </div>

</div>

<div class="blog-comment">
  <h3 class="text-success">Comments:</h3>
  <% if current_user %>
    <%= render partial: 'vcomments/form', locals: { video: @video , parent: nil, user: current_user, cancel: false} %>
  <% end %>

  <hr/>
  <div class="d-flex justify-content-center mb-5">
    <% if current_user %>
      <ul class="comments w-100">
        <turbo-frame id="video-comments_<%= @video.id %>">
          <% if @video.vcomments.count > 0 %>
            <%= render "vcomments/vcomments", video: @video %>
          <% else %>
            <b>No comments here!!! 😢😢😢</b>
          <% end %>
        </turbo-frame>
      </ul>
    <% else %>
      <% if @video.vcomments.count > 0 %>
        <ul class="comments w-100">
          <%= render "vcomments/vcomments_for_guest" , vcomments: @video.vcomments.where(parent_id: nil) %>
        </ul>
      <% else %>
        No comments here!!! 😢😢😢
      <% end %>
    <% end %>
  </div>


</div>