config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  # get '/:locale' => 'home#index'
  devise_for :users,controllers:{
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # action home page
  get '/posts', to: "home#index_show_post", as: 'posts_index'
  post '/posts', to: "home#index_show_post", as: 'get_post_index_pagy'
  get '/videos', to: "home#index_show_video", as: 'videos_index'
  post '/videos', to: "home#index_show_video", as: 'get_video_index_pagy'

  # action admin
  namespace 'admin' do
    get :index_ban_user, to: "users#index_ban_user"
    resources :users do
      member do
        get :action_ban_user
        get :action_unban_user
        post :ban_user
        post :unban_user
      end
    end
    resources :posts do
      member do
        get :action_accept_post
        get :action_refuse_post
        post :accept_post
        post :refuse_post
      end
    end
    resources :videos do
      member do
        get :action_accept_video
        get :action_refuse_video
        post :accept_video
        post :refuse_video
      end
    end
  end

  # action user
  scope '/users' do
    resources :posts do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_post
      end
      resources :elements
      resources :comments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
    resources :videos do
      member do
        patch :vote
        patch :bookmark
        post :unpublish
        post :publish
        get :action_delete_video
      end
      resources :vcomments, only: [:create, :destroy] do
        member do
          patch :vote
        end
      end
    end
  end

  resources :chats do
    resources :messages
  end
  resources :tags do
    member do
      post :show, as: 'get_posts_tag_index_pagy'
      get :show_video
      post :show_video, as: 'get_videos_tag_index_pagy'
      post :added_tag
    end
  end
  resources :profile, only:  [:show] do
    member do
      post :follow
      delete :unfollow
      get :action_report_user
      post :report_user
    end
  end
  resources :dashboard do
    collection do
      # get :user_followers
      get :following_tags
      get :following_users
      get :posts_bookmark
      post :posts_bookmark, as: 'get_posts_dashboard_pagy'
      get :videos_bookmark
      post :videos_bookmark, as: 'get_videos_dashboard_pagy'
      get :notifications
    end
  end

  # action search
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'
  get 'search', to: 'search#search_all', as: 'search_all'
  get 'show_all_user_search', to: 'search#show_all_user_search', as: :show_all_user_search

  # View Object Notification
  get '/notification/:id', to: 'notification#view_object', as: 'view_object'
end

app/views/shared/_error.html.erb
<div style="color: red">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this post from being saved:</h2>

  <ul>
    <% object.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_header.html.erb
<div class="header sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light primary-bg d-flex">
    <div class="container-xl">
      <button class="btn btn-primary d-block d-md-none" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
        <i class="fa-solid fa-bars"></i>
      </button>
      <div class="d-flex align-items-center col-7 col-md-8">
        <%= link_to root_path, class: "navbar-brand text-white" do %>
          <%= image_tag("myblog-logo.png", alt: "MyBlog", class: "rounded-3", style: "height: 40px") %>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon text-white"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item search-nav-item">
              <%= render partial: "search/form", locals: {users: [], posts: [], videos: []} %>
            </li>
          </ul>
        </div>

      </div>
      <div class="d-flex align-items-center col-3 col-md-4 justify-content-end">
        <% if user_signed_in? %>
          <div class="float-right">
            <ul class="nav float-right">
              <div class="dropdown d-flex align-items-center">
                <%= link_to t('user.post.object.create'), new_post_path, class: 'btn btn-outline-light mx-2' %>
                <% if current_user %>
                  <%= turbo_stream_from "notifications_#{current_user.id}" %>
                  <%= turbo_frame_tag "notifications_#{current_user.id}" do %>
                    <%= render 'shared/notifications', user: current_user %>
                  <% end %>
                <% end %>

                <a href="#" class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown">
                  <% if current_user.avatar.attached? %>
                    <%= image_tag(current_user.avatar, alt: "#{current_user.username}", class: "avatar-image rounded-circle", id: "avatarUserHeader") %>
                  <% else %>
                    <%= image_tag("user.jpg", alt: "#{current_user.username}", class: "avatar-image rounded-circle", id: "avatarUserHeader") %>
                  <% end %>
                </a>
                <ul class="dropdown-menu" style="left: 50%; width: 50%" aria-labelledby="dropdownMenuButton1">
                  <li><%= link_to current_user.username, profile_path(current_user.id), class: "my-2 my-sm-0 dropdown-item" %></li>
                  <hr/>
                  <li><%= link_to "🏠 Dashboard", dashboard_index_path, class: "my-2 my-sm-0 dropdown-item" %></li>
                  <li><%= link_to "🖋 #{t('user.post.object.user_post')}", posts_path, class: "my-2 my-sm-0 dropdown-item" %></li>
                  <li><%= link_to "📼 My Videos", videos_path, class: "my-2 my-sm-0 dropdown-item" %></li>

                  <hr/>
                  <li><%= link_to "👤 Edit account", edit_user_registration_path, class: "my-2 my-sm-0 dropdown-item" %></li>
                  <li><%= button_to "🚫 Sign out", destroy_user_session_path, class: "my-2 my-sm-0 dropdown-item", method: :delete %></li>
                </ul>
              </div>
            </ul>
          </div>
        <% else %>
          <%= link_to "Sign in", new_user_session_path,class: 'btn btn-outline-light my-2 my-sm-0', method: :get %>
        <% end %>
        <ul>
          <%= link_to "🇻🇳", url_for(locale: "vi"), class: "text-white" %>
          <span class="text-white">|</span>
          <%= link_to "🇬🇧", url_for(locale: "en"), class: "text-white" %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_notifications.html.erb
<li class="nav-item dropdown " style="font-size: 19px;">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="badge rounded-pill bg-danger">
      <%= user.received_notifications.where(as_read: false).count >= 9 ? "9+" : user.received_notifications.where(as_read: false).count %> 📩
    </span>
  </a>
  <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
    <% user.received_notifications.where(as_read: false).order(created_at: :desc).limit(9).each do |notification| %>
      <li class="dropdown-item">
        <%= content_tag(:div) do %>
          <div class="card" style="border: none;">
            <div class="card-header d-flex justify-content-between align-items-center rounded-2" style="border: none; background-color: #EFEFEF;">
              <div>
                <%= link_to "🔔 #{notification.content}",
                            view_object_path(notification),
                            data:{turbo: false},
                            style: if notification.healthy?
                                     notification.as_read? ? "color: #3887BE;" : "color: #E36414;"
                                   else
                                     "color: #B80000;"
                                   end %>
              </div>
              <div class="ms-2">
                <b>Created</b> <%= time_ago_in_words(notification.created_at) %> ago
              </div>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
    <li class="dropdown-item">
      <%= content_tag(:div) do %>
        <div class="card" style="border: none;">
          <div class="card-header d-flex justify-content-center align-items-center rounded-2" style="border: none; background-color: #EFEFEF;">
            <div>
              <%= link_to "View all your notifications!!!", notifications_dashboard_index_path, data:{turbo: false}, class: "text-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </li>
  </ul>
</li>

app/views/shared/_side_bar_left_item.html.erb
<% if user_signed_in? %>
  <ul class="nav flex-column px-3">
    <% if current_user.user? %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.blank?) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🐧 #{t('home')}", root_path, class: "nav-link text-black"%>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("posts") && !path.include?("users") && !path.include?("admin")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📰 #{t('user.post.object.posts')}", posts_index_path(index: "top"), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("videos") && !path.include?("users")) && !path.include?("profile") && !path.include?("admin") }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📹 Videos", videos_index_path(index: "top"), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("users") && path.include?("posts") && (path.size < 3)) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🖋 #{t('user.post.object.user_post')}", posts_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("users") && path.include?("videos") && (path.size < 3)) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📼 My Videos", videos_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("tags") )}") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🏷 #{t('user.tag.tags')}", tags_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("profile") && (path[1]==current_user.id.to_s))}") do %>
        <div class="d-flex align-items-center">
          <%= link_to "#{current_user.male?? "👦":"👩"} #{t('user.profile.my_profile')}", profile_path(current_user.id), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item") do %>
        <div class="d-flex align-items-center">
          <%= link_to "💬 ChatAI", chats_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "nav-item mt-3") do %>
        <div class="d-flex align-items-center">
          <p class="px-2">
            <i class="fa-brands fa-twitter fa-xl "></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-square-facebook fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-github fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-square-instagram fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-twitch fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-tiktok fa-xl"></i>
          </p>
        </div>
      <% end %>
    <% end %>

    <% if current_user.admin? %>

      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.blank?) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🐧 #{t('home')}", root_path, class: "nav-link text-black"%>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("posts") && !path.include?("users") && !path.include?("admin")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📰 #{t('user.post.object.posts')}", posts_index_path(index: "top"), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("videos") && !path.include?("users")) && !path.include?("profile") && !path.include?("admin") }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📹 Videos", videos_index_path(index: "top"), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("users") && path.include?("posts") && (path.size < 3)) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🖋 #{t('user.post.object.user_post')}", posts_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("users") && path.include?("videos") && (path.size < 3)) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📼 My Videos", videos_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("tags") )}") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🏷 #{t('user.tag.tags')}", tags_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("profile") && (path[1]==current_user.id.to_s))}") do %>
        <div class="d-flex align-items-center">
          <%= link_to "#{current_user.male?? "👦":"👩"} #{t('user.profile.my_profile')}", profile_path(current_user.id), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item") do %>
        <div class="d-flex align-items-center">
          <%= link_to "💬 ChatAI", chats_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "nav-item mt-3") do %>
        <div class="d-flex align-items-center">
          <p class="px-2">
            <i class="fa-brands fa-twitter fa-xl "></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-square-facebook fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-github fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-square-instagram fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-twitch fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-tiktok fa-xl"></i>
          </p>
        </div>
      <% end %>
      <hr/>

      <h3 class="nav-title"> Admin</h3>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("admin") && path.include?("users")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "⚙ #{t('admin.user.user_management.management')}", admin_users_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("admin") && path.include?("posts")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "⚙ Post moderation", admin_posts_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("admin") && path.include?("videos")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "⚙ Video moderation", admin_videos_path, class: "nav-link text-black" %>
        </div>
      <% end %>
    <% end %>

    <% if current_user.censor? %>

      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.blank?) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🐧 #{t('home')}", root_path, class: "nav-link text-black"%>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("posts") && !path.include?("users") && !path.include?("admin")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📰 #{t('user.post.object.posts')}", posts_index_path(index: "top"), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("videos") && !path.include?("users")) && !path.include?("profile") && !path.include?("admin") }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📹 Videos", videos_index_path(index: "top"), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("users") && path.include?("posts") && (path.size < 3)) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🖋 #{t('user.post.object.user_post')}", posts_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("users") && path.include?("videos") && (path.size < 3)) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "📼 My Videos", videos_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("tags") )}") do %>
        <div class="d-flex align-items-center">
          <%= link_to "🏷 #{t('user.tag.tags')}", tags_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("profile") && (path[1]==current_user.id.to_s))}") do %>
        <div class="d-flex align-items-center">
          <%= link_to "#{current_user.male?? "👦":"👩"} #{t('user.profile.my_profile')}", profile_path(current_user.id), class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item") do %>
        <div class="d-flex align-items-center">
          <%= link_to "💬 ChatAI", chats_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "nav-item mt-3") do %>
        <div class="d-flex align-items-center">
          <p class="px-2">
            <i class="fa-brands fa-twitter fa-xl "></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-square-facebook fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-github fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-square-instagram fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-twitch fa-xl"></i>
          </p>
          <p class="px-2">
            <i class="fa-brands fa-tiktok fa-xl"></i>
          </p>
        </div>
      <% end %>
      <hr/>

      <h3 class="nav-title"> Censor</h3>

      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("admin") && path.include?("posts")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "⚙ Post moderation", admin_posts_path, class: "nav-link text-black" %>
        </div>
      <% end %>
      <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("admin") && path.include?("videos")) }") do %>
        <div class="d-flex align-items-center">
          <%= link_to "⚙ Video moderation", admin_videos_path, class: "nav-link text-black" %>
        </div>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <ul class="nav flex-column px-3">
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.blank?) }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "🐧 #{t('home')}", root_path, class: "nav-link text-black"%>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("posts") && !path.include?("users")) }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "📰 #{t('user.post.object.posts')}", posts_index_path(index: "top"), class: "nav-link text-black" %>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("videos") && !path.include?("users")) && !path.include?("profile") && !path.include?("admin") }") do %>
      <div class="d-flex align-items-center">
        <%= link_to "📹 Videos", videos_index_path, class: "nav-link text-black" %>
      </div>
    <% end %>
    <%= content_tag(:li,class: "hover-animation-nav-item nav-item #{"active" if(path.include?("tags") )}") do %>
      <div class="d-flex align-items-center">
        <%= link_to "🏷 #{t('user.tag.tags')}", tags_path, class: "nav-link text-black" %>
      </div>
    <% end %>
  </ul>
<% end %>

app/views/shared/_slide_bar_left.html.erb
<div class="sidebar-left pt-5 col-2 d-none d-md-block ">
  <div class="sidebar-sticky pt-4">
    <%= render "shared/side_bar_left_item", path: path %>
  </div>
</div>

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Tab Menu</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <%= render "shared/side_bar_left_item", path: path %>
  </div>
</div>

app/views/shared/_slide_bar_right.html.erb
<nav id="slideBarRight" class="col-2 sidebar-right pt-5 d-none d-md-block">
  <div class="col-md-10 mt-5">
    <div class="profile-card text-center shadow bg-light p-4 rounded-3">
<!--      <h3 class="pt-3 text-dark">KLTN-HCMUTE</h3>-->
      <p class="text-secondary">Made by <span style="text-decoration: underline">TaQuocAnh</span></p>
      <p class="text-secondary">Contact:</p>
      <div class="social-links">
        <ul>
          <li><a href="https://www.facebook.com/tqanhute" target=”_blank” ><i class="fa-brands fa-facebook"></i></a></li>
          <li><a href="mailto:quocanhute@gmail.com"><i class="fa-solid fa-at"></i></a></li>
          <li><a href="https://github.com/quocanhute/" target=”_blank”><i class="fa-brands fa-github"></i></a></li>
          <li><a href="https://www.linkedin.com/in/taquocanh/" target=”_blank”><i class="fa-brands fa-linkedin"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <% if @user_with_tag %>
    <div class="col-md-10 mt-5">
      <h4>Who follow this tag:</h4>
      <div class="d-flex flex-column px-3 py-3">
        <% @tag.users.each do |user| %>
          <div>
            <% if user.avatar.attached? %>
              <%= image_tag(user.avatar, alt: "#{user.username}", class: "avatar-image rounded-circle", id: "avatarUserHeader") %>
            <% else %>
              <%= image_tag("user.jpg", alt: "#{user.username}", class: "avatar-image rounded-circle", id: "avatarUserHeader") %>
            <% end %>
            <%= link_to "#{user.username }", profile_path(user),data:{turbo: false},class: "mx-1 text-dark" %>
          </div>
          <hr/>
          <br>
        <% end %>
      </div>
    </div>
  <% end %>
</nav>

app/views/shared/_static_button_page.html.erb
<% if pages == "post" %>
  <div class="d-flex justify-content-center">
    <button id="postButton" class="btn btn-secondary mx-1 primary-color"><%= link_to "POSTS", posts_index_path,class: "text-white"%></button>
    <button id="photoButton" class="btn primary-bg mx-1"><%= link_to "PHOTOS", photos_index_path, class: "text-white"%></button>
  </div>
<% elsif pages == "photo"%>
  <div class="d-flex justify-content-center">
    <button id="postButton" class="btn primary-bg mx-1"><%= link_to "POSTS", posts_index_path,class: "text-white"%></button>
    <button id="photoButton" class="btn btn-secondary mx-1 primary-color"><%= link_to "PHOTOS", photos_index_path, class: "text-white"%></button>
  </div>
<% else %>
  <div class="d-flex justify-content-center">
    <button id="postButton" class="btn primary-bg mx-1"><%= link_to "POSTS", posts_index_path,class: "text-white"%></button>
    <button id="photoButton" class="btn primary-bg mx-1"><%= link_to "PHOTOS", photos_index_path, class: "text-white"%></button>
  </div>
<%end %>